@echo off
start ohhellnawyourerecked
start narrator.exe
start mrt
start wordpad
start control
start perfmon
start wmplayer.exe
start finger.exe
start osk.exe
start ftp.exe
start hdwwiz
start dccw
start cmd
start dialer
start iexpress
start eventvwr.msc
start magnify
start notepad
start ms-settings:
start colorcpl
start cleanmgr
start services.msc
start compmgmt.msc
start dcomcnfg
start msinfo32
start winver
start dxdiag
start msra
start perfmon
start cttune
start C:\Windows\SysWOW64\odbcad32.exe
start mstsc
start taskmgr
start attrib.exe
start auditpol.exe
start cacls.exe
start bitsadmin.exe
start powershell.exe
start at.exe
start cipher.exe
start choice.exe
start clip.exe
start cliconfg.exe
start PowerShell_ISE.exe
start cmstp.exe
start msconfig.exe
start notepad
start taskschd.msc
start WF.msc
start quickassist.exe
start mspaint.exe
start psr.exe
start SnippingTool.exe
start dfrgui.exe
start regedit.exe
start iscsicpl.exe
start dfrgui.exe
start MdSched.exe